### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for 'model/pytorch_model-00001-of-00008.bin' at 'model/pytorch_model-00001-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by lyb19930105** [SmartFlowAI/EmoLLM#199]
环境：ubuntu20.04，双4090显卡
按照部署教程 https://github.com/SmartFlowAI/EmoLLM/blob/main/docs/quick_start.md 部署aiwei模型没问题，但在部署EmoLLM_internlm2_7b_full模型（https://openxlab.org.cn/models/detail/ajupyter/EmoLLM_internlm2_7b_full/tree/main） 时报了以上错误，完整错误信息如下：
(emollm) root@alchemy-9kud3rkkjs:/init/projects/EmoLLM# streamlit run web_internlm2.py --server.address=0.0.0.0 --server.port 9527

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:9527

/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
load model begin.
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/8 [00:00<?, ?it/s]
2024-04-18 13:40:25.161 Uncaught app exception
Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 523, in load_state_dict
    if f.read(7) == "version":
  File "/init/miniconda3/envs/emollm/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/init/projects/EmoLLM/web_internlm2.py", line 271, in <module>
    main()
  File "/init/projects/EmoLLM/web_internlm2.py", line 215, in main
    model, tokenizer = load_model()
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/init/projects/EmoLLM/web_internlm2.py", line 167, in load_model
    AutoModelForCausalLM.from_pretrained("model", trust_remote_code=True)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4091, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 535, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'model/pytorch_model-00001-of-00008.bin' at 'model/pytorch_model-00001-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
load model begin.
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/8 [00:00<?, ?it/s]
2024-04-18 13:40:27.044 Uncaught app exception
Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 523, in load_state_dict
    if f.read(7) == "version":
  File "/init/miniconda3/envs/emollm/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/init/projects/EmoLLM/web_internlm2.py", line 271, in <module>
    main()
  File "/init/projects/EmoLLM/web_internlm2.py", line 215, in main
    model, tokenizer = load_model()
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/init/projects/EmoLLM/web_internlm2.py", line 167, in load_model
    AutoModelForCausalLM.from_pretrained("model", trust_remote_code=True)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4091, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 535, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'model/pytorch_model-00001-of-00008.bin' at 'model/pytorch_model-00001-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by lyb19930105** [comment]
按照错误提示，我修改了web_internlm2.py中的load_model()函数，改为
`@st.cache_resource
def load_model():
    model = (
        AutoModelForCausalLM.from_pretrained("model", trust_remote_code=True,from_tf=True)
        .to(torch.bfloat16)
        .cuda()
    )
    tokenizer = AutoTokenizer.from_pretrained("model", trust_remote_code=True,from_tf=True)
    return model, tokenizer`
则报以下新的错误：
(emollm) root@alchemy-9kud3rkkjs:/init/projects/EmoLLM# streamlit run web_internlm2.py --server.address=0.0.0.0 --server.port 9527

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:9527

/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
load model begin.
2024-04-18 14:11:20.647 Uncaught app exception
Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/init/projects/EmoLLM/web_internlm2.py", line 271, in <module>
    main()
  File "/init/projects/EmoLLM/web_internlm2.py", line 215, in main
    model, tokenizer = load_model()
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/init/projects/EmoLLM/web_internlm2.py", line 167, in load_model
    AutoModelForCausalLM.from_pretrained("model", trust_remote_code=True,from_tf=True)
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3665, in from_pretrained
    if resolved_archive_file.endswith(".index"):
AttributeError: 'list' object has no attribute 'endswith'

**Comment by aJupyter** [comment]
@HatBoy

**Comment by aJupyter** [comment]
> 环境：ubuntu20.04，双4090显卡 按照部署教程 https://github.com/SmartFlowAI/EmoLLM/blob/main/docs/quick_start.md 部署aiwei模型没问题，但在部署EmoLLM_internlm2_7b_full模型（[https://openxlab.org.cn/models/detail/ajupyter/EmoLLM_internlm2_7b_full/tree/main）](https://openxlab.org.cn/models/detail/ajupyter/EmoLLM_internlm2_7b_full/tree/main%EF%BC%89) 时报了以上错误，完整错误信息如下： (emollm) root@alchemy-9kud3rkkjs:/init/projects/EmoLLM# streamlit run web_internlm2.py --server.address=0.0.0.0 --server.port 9527
> 
> Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
> 
> You can now view your Streamlit app in your browser.
> 
> URL: http://0.0.0.0:9527
> 
> /init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. _torch_pytree._register_pytree_node( /init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. _torch_pytree._register_pytree_node( /init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. _torch_pytree._register_pytree_node( load model begin. Loading checkpoint shards: 0%| | 0/8 [00:00<?, ?it/s] 2024-04-18 13:40:25.161 Uncaught app exception Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value cached_result = cache.read_result(value_key) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result raise CacheKeyNotFoundError() streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss cached_result = cache.read_result(value_key) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result raise CacheKeyNotFoundError() streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict return torch.load(checkpoint_file, map_location=map_location) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 1005, in load with _open_zipfile_reader(opened_file) as opened_zipfile: File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 457, in **init** super().**init**(torch._C.PyTorchFileReader(name_or_buffer)) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 523, in load_state_dict if f.read(7) == "version": File "/init/miniconda3/envs/emollm/lib/python3.9/codecs.py", line 322, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "/init/projects/EmoLLM/web_internlm2.py", line 271, in main() File "/init/projects/EmoLLM/web_internlm2.py", line 215, in main model, tokenizer = load_model() File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper return cached_func(*args, **kwargs) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in **call** return self._get_or_create_cached_value(args, kwargs) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value return self._handle_cache_miss(cache, value_key, func_args, func_kwargs) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss computed_value = self._info.func(*func_args, **func_kwargs) File "/init/projects/EmoLLM/web_internlm2.py", line 167, in load_model AutoModelForCausalLM.from_pretrained("model", trust_remote_code=True) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained return model_class.from_pretrained( File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained ) = cls._load_pretrained_model( File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4091, in _load_pretrained_model state_dict = load_state_dict(shard_file) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 535, in load_state_dict raise OSError( OSError: Unable to load weights from pytorch checkpoint file for 'model/pytorch_model-00001-of-00008.bin' at 'model/pytorch_model-00001-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. load model begin. Loading checkpoint shards: 0%| | 0/8 [00:00<?, ?it/s] 2024-04-18 13:40:27.044 Uncaught app exception Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value cached_result = cache.read_result(value_key) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result raise CacheKeyNotFoundError() streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss cached_result = cache.read_result(value_key) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result raise CacheKeyNotFoundError() streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict return torch.load(checkpoint_file, map_location=map_location) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 1005, in load with _open_zipfile_reader(opened_file) as opened_zipfile: File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/torch/serialization.py", line 457, in **init** super().**init**(torch._C.PyTorchFileReader(name_or_buffer)) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 523, in load_state_dict if f.read(7) == "version": File "/init/miniconda3/envs/emollm/lib/python3.9/codecs.py", line 322, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "/init/projects/EmoLLM/web_internlm2.py", line 271, in main() File "/init/projects/EmoLLM/web_internlm2.py", line 215, in main model, tokenizer = load_model() File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper return cached_func(*args, **kwargs) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in **call** return self._get_or_create_cached_value(args, kwargs) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value return self._handle_cache_miss(cache, value_key, func_args, func_kwargs) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss computed_value = self._info.func(*func_args, **func_kwargs) File "/init/projects/EmoLLM/web_internlm2.py", line 167, in load_model AutoModelForCausalLM.from_pretrained("model", trust_remote_code=True) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained return model_class.from_pretrained( File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained ) = cls._load_pretrained_model( File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4091, in _load_pretrained_model state_dict = load_state_dict(shard_file) File "/init/miniconda3/envs/emollm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 535, in load_state_dict raise OSError( OSError: Unable to load weights from pytorch checkpoint file for 'model/pytorch_model-00001-of-00008.bin' at 'model/pytorch_model-00001-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
您好，感谢您的关注。
7B full可以用下面的链接下载 或许能解决问题
https://www.modelscope.cn/models/zhouxinao/7b_full/

**Comment by HatBoy** [comment]
经过实测发现，openxlab平台上的[EmoLLM_internlm2_7b_full](https://openxlab.org.cn/models/detail/ajupyter/EmoLLM_internlm2_7b_full/tree/main)模型存在未知问题，运行不起来。重新将新的7b_full模型上传到https://www.modelscope.cn/models/zhouxinao/7b_full/后经过测试可以正常运行。需要注意两点：
1、[download_model.py](https://github.com/SmartFlowAI/EmoLLM/blob/main/download_model.py)脚本当前只支持openxlab平台模型的下载，modelscope平台的模型不支持，需要手动下载或者使用modelscope提供的modelscope.hub..snapshot_download("zhouxinao/7b_full", cache_dir="./")函数下载。
2、默认app.py调用的是[web_internlm2.py](https://github.com/SmartFlowAI/EmoLLM/blob/main/web_internlm2.py)脚本，该脚本近期加入了RAG功能，需要其他配置才能运行起来；可使用调用[web_demo-aiwei.py](https://github.com/SmartFlowAI/EmoLLM/blob/main/web_demo-aiwei.py)脚本来运行7b_full模型。
@lyb19930105
