### ISSUE TITLE
部署InternLM2_5_7B_chat报错：ModuleNotFoundError: No module named 'transformers_modules.EmoLLM_V3'

### ISSUE THREAD

**Issue by zhy844694805** [SmartFlowAI/EmoLLM#291]
运行web_internlm2_5.py之后报错ModuleNotFoundError: No module named 'transformers_modules.EmoLLM_V3'，感谢大佬解答

**Comment by aJupyter** [comment]
用的哪个代码？

**Comment by zhy844694805** [comment]
> 用的哪个？

大佬您好，我运行的是本项目里的web_internlm2_5.py

**Comment by zhy844694805** [comment]
环境配置安装了requirements.txt，transformers更新到了最新版本，python=3.10， 从modelscope下载了2次chg0901/EmoLLMV3.0 完整的模型，感谢大佬解答

**Comment by zhy844694805** [comment]
(emollm) tuohai@tuohaiserver3:~/EmoLLM$ python web_internlm2_5.py 
/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
fatal: destination path './EmoLLM_V3.0' already exists and is not an empty directory.
load model begin.
2024-08-30 17:22:17.811 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run web_internlm2_5.py [ARGUMENTS]
Traceback (most recent call last):
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tuohai/EmoLLM/web_internlm2_5.py", line 299, in <module>
    main()
  File "/home/tuohai/EmoLLM/web_internlm2_5.py", line 245, in main
    model, tokenizer = load_model()
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/home/tuohai/EmoLLM/web_internlm2_5.py", line 192, in load_model
    model = (AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True).to(torch.bfloat16).cuda())
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1091, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/home/tuohai/miniconda3/envs/emollm/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.EmoLLM_V3'

**Comment by aJupyter** [comment]
有时间我看一下哈

**Comment by aJupyter** [comment]
可以试试cli能不能启动

**Comment by deng1fan** [comment]
同问，同样的问题，换了好多 transformers 库版本 都不行
